### ISSUE TITLE
github enterprise support?

### ISSUE THREAD

**Issue by butterywombat** [neoclide/coc-git#113]
Is it possible to support github enterprise? I know https://github.com/tpope/vim-rhubarb has some  options available to set-I'm using this but would love the other coc-git commands. Several of the coc commands don't work for me (such as copyUrl, openBrowser etc)

**Comment by chemzqm** [comment]
I don't have github enterprise, don't know how to support it.

**Comment by CallumHoward** [comment]
I modified another plugin to work with GitHub Enterprise previously (I don't have it anymore). The problem is just that the domain is assumed to be `github.com`. Instead I grabbed the domain from the first remote of the repo, so it could be `company.github.com` for example.
I think it otherwise behaves the same as normal GitHub.
