### ISSUE TITLE
Feature request: highlight merge conflict sections

### ISSUE THREAD

**Issue by xaljer** [neoclide/coc-git#115]
Like VS Code, highlight the git merge conflict sections and give commands to select one of branch to merge.

**Comment by xaljer** [comment]
![image](https://user-images.githubusercontent.com/8309631/83319247-4d4a3580-a26f-11ea-9036-b3ae2f620b95.png)
Like above.
- Accept current change
- Accept incoming change
- Accept both change

**Comment by yannham** [comment]
I've been trying to tackle this issue, but it seems there's a bug in the Neovim's API `buffer.addHighlight` function. The documentation states:

> `addHighlight({ hlGroup: _hlGroup, line, colStart: _start, colEnd: _end, srcId: _srcId, }: BufferHighlight): Promise<number | null>;`
> [...]
> When called with src_id = 0, an unique source id is generated and returned.

When highlighting conflicts, one needs to have them in a unique, distinct highlight group, in order to clear the highlights once the source change and the conflict list is updated without messing with other plugin's highlighting. However in practice this function returns `null` when `srcId` is set to `0`, so there's no reliable way to generate a fresh `srcId` to highlight conflicts.

@chemzqm, coc-git uses your fork of the [neovim node client](https://github.com/neovim/node-client/), but I imagine it's not affecting this kind of basic function ? Should I file an issue in the original node-client's repo ?

**Comment by chemzqm** [comment]
Use nvim.createNamespace

**Comment by chemzqm** [comment]
Bug of my node-client.
